### ISSUE TITLE
The ACE Checker report not generated for common images epub file

### ISSUE THREAD

**Issue by coolharisha** [daisy/ace#192] opened 2018-06-07 14:17 UTC
Please provide the following details if possible or relevant:

- [1.0.2] the version of Ace impacted by the issue (as returned by the `ace -v` command).
- [9.3.0] the version of Node used to run Ace (as returned by the `node -v` command).
- [window 10] your operating system and version.
- [error:   Unexpected error: EBUSY: resource busy or locked, copyfile 'D:\hari\2018\06-JUN\07-JUN\ACE Testing\9780310356394_EPUB\OEBPS\images\common.jpg' -> 'D:\hari\2018\06-JUN\07-JUN\ACE Testing\ACE12\data\OEBPS\images\common.jpg'
info:    Closing logs.
Re-run Ace using the --verbose option to enable full debug logging.] if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).
- [not generated] if the issue is about the HTML report: the browser(s) and version(s) you used.
- [sorry sir, The content have copyright] if possible, let us know if you can share a sample input file to help us reproduce the issue.

**Comment by rdeltour** [comment] 2018-06-07 14:49
Thanks for the report.

Does the error happen systematically with this EPUB sample and with the same file (common.jpg)?
What’s specific about "common.jpg", is it used in more than one content document?

If the content is copyrighted, you could possibly send it to me privately via email (I will delete it as soon as the bug is identified), or I could also possibly sign an NDA.

**Comment by RajeshVimal** [comment] 2018-06-08 07:01
Yes. The image "common.jpg" has been used in many instances in different html files. The common image has been used around 102 instances inside the ePub. 

Please see the log. if this is OK to solve the issue. if ePub is required, i will check with the customer and get back to you.

I assume that, the common image seems to be verifying multiple times inside the image folder in order to generate a report. But the only one common image exist in the folder, It failed to create a report.

D:\Rajeshkumar\Works\Test\Ace>ace -o report --verbose D:\Rajeshkumar\Works\Test\Ace\ISBN_EPUB.epub
verbose: Ace 1.0.2, Node v8.10.0, Windows_NT 10.0.10240
verbose: Options: cwd=D:\Rajeshkumar\Works\Test\Ace, outdir=report, tmpdir=undefined, verbose=true, silent=false, jobId=
info:    Processing D:\Rajeshkumar\Works\Test\Ace\ISBN_EPUB.epub
verbose: Extracting EPUB
info:    Parsing EPUB
verbose: at location 'C:\Users\AM3617\AppData\Local\Temp\tmp-10480H2yz6sn4eK9d'
info:    Analyzing accessibility metadata
info:    Checking package...
info:    - OEBPS\content.opf: No issues found
info:    Checking documents...
verbose: - Processing text/cover.xhtml
verbose: - Processing text/chapter01.xhtml
verbose: - Processing text/chapter02.xhtml
verbose: - Processing text/titlepage.xhtml
verbose: Converting aXe results to ace for text/cover.xhtml
info:    - text/cover.xhtml: No issues found
verbose: - Processing text/copyright-page.xhtml
verbose: Converting aXe results to ace for text/chapter01.xhtml
info:    - text/chapter01.xhtml: No issues found
verbose: - Processing text/dedication.xhtml
verbose: Converting aXe results to ace for text/titlepage.xhtml
info:    - text/titlepage.xhtml: No issues found
verbose: - Processing text/contents.xhtml
verbose: Converting aXe results to ace for text/chapter02.xhtml
info:    - text/chapter02.xhtml: No issues found
verbose: - Processing text/chapter03.xhtml
verbose: Converting aXe results to ace for text/dedication.xhtml
info:    - text/dedication.xhtml: No issues found
verbose: - Processing text/chapter04.xhtml
verbose: Converting aXe results to ace for text/copyright-page.xhtml
info:    - text/copyright-page.xhtml: No issues found
verbose: - Processing text/chapter05.xhtml
verbose: Converting aXe results to ace for text/chapter03.xhtml
info:    - text/chapter03.xhtml: No issues found
verbose: - Processing text/chapter06.xhtml
verbose: Converting aXe results to ace for text/contents.xhtml
info:    - text/contents.xhtml: No issues found
verbose: - Processing text/chapter07.xhtml
verbose: Converting aXe results to ace for text/chapter04.xhtml
info:    - text/chapter04.xhtml: No issues found
verbose: - Processing text/chapter08.xhtml
verbose: Converting aXe results to ace for text/chapter06.xhtml
info:    - text/chapter06.xhtml: No issues found
verbose: - Processing text/chapter09.xhtml
verbose: Converting aXe results to ace for text/chapter05.xhtml
info:    - text/chapter05.xhtml: No issues found
verbose: - Processing text/chapter09a.xhtml
verbose: Converting aXe results to ace for text/chapter07.xhtml
info:    - text/chapter07.xhtml: No issues found
verbose: - Processing text/chapter10.xhtml
verbose: Converting aXe results to ace for text/chapter08.xhtml
info:    - text/chapter08.xhtml: No issues found
verbose: - Processing text/chapter11.xhtml
verbose: Converting aXe results to ace for text/chapter09a.xhtml
info:    - text/chapter09a.xhtml: No issues found
verbose: - Processing text/chapter12.xhtml
verbose: Converting aXe results to ace for text/chapter09.xhtml
info:    - text/chapter09.xhtml: No issues found
verbose: - Processing text/chapter13.xhtml
verbose: Converting aXe results to ace for text/chapter10.xhtml
info:    - text/chapter10.xhtml: No issues found
verbose: - Processing text/chapter14.xhtml
verbose: Converting aXe results to ace for text/chapter11.xhtml
info:    - text/chapter11.xhtml: No issues found
verbose: - Processing text/chapter15.xhtml
verbose: Converting aXe results to ace for text/chapter12.xhtml
info:    - text/chapter12.xhtml: No issues found
verbose: - Processing text/chapter16.xhtml
verbose: Converting aXe results to ace for text/chapter13.xhtml
info:    - text/chapter13.xhtml: No issues found
verbose: - Processing text/chapter17.xhtml
verbose: Converting aXe results to ace for text/chapter16.xhtml
info:    - text/chapter16.xhtml: No issues found
verbose: - Processing text/chapter18.xhtml
verbose: Converting aXe results to ace for text/chapter17.xhtml
info:    - text/chapter17.xhtml: No issues found
verbose: - Processing text/chapter19.xhtml
verbose: Converting aXe results to ace for text/chapter15.xhtml
info:    - text/chapter15.xhtml: No issues found
verbose: - Processing text/chapter20.xhtml
verbose: Converting aXe results to ace for text/chapter14.xhtml
info:    - text/chapter14.xhtml: No issues found
verbose: - Processing text/chapter21.xhtml
verbose: Converting aXe results to ace for text/chapter18.xhtml
info:    - text/chapter18.xhtml: No issues found
verbose: - Processing text/chapter22.xhtml
verbose: Converting aXe results to ace for text/chapter19.xhtml
info:    - text/chapter19.xhtml: No issues found
verbose: - Processing text/chapter23.xhtml
verbose: Converting aXe results to ace for text/chapter20.xhtml
info:    - text/chapter20.xhtml: No issues found
verbose: - Processing text/chapter24.xhtml
verbose: Converting aXe results to ace for text/chapter21.xhtml
info:    - text/chapter21.xhtml: No issues found
verbose: - Processing text/chapter25.xhtml
verbose: Converting aXe results to ace for text/chapter22.xhtml
info:    - text/chapter22.xhtml: No issues found
verbose: - Processing text/chapter26.xhtml
verbose: Converting aXe results to ace for text/chapter23.xhtml
info:    - text/chapter23.xhtml: No issues found
verbose: - Processing text/chapter27.xhtml
verbose: Converting aXe results to ace for text/chapter24.xhtml
info:    - text/chapter24.xhtml: No issues found
verbose: - Processing text/chapter28.xhtml
verbose: Converting aXe results to ace for text/chapter25.xhtml
info:    - text/chapter25.xhtml: No issues found
verbose: - Processing text/chapter29.xhtml
verbose: Converting aXe results to ace for text/chapter27.xhtml
info:    - text/chapter27.xhtml: No issues found
verbose: - Processing text/chapter30.xhtml
verbose: Converting aXe results to ace for text/chapter28.xhtml
info:    - text/chapter28.xhtml: No issues found
verbose: - Processing text/chapter31.xhtml
verbose: Converting aXe results to ace for text/chapter26.xhtml
info:    - text/chapter26.xhtml: No issues found
verbose: - Processing text/chapter32.xhtml
verbose: Converting aXe results to ace for text/chapter29.xhtml
info:    - text/chapter29.xhtml: No issues found
verbose: - Processing text/chapter33.xhtml
verbose: Converting aXe results to ace for text/chapter31.xhtml
info:    - text/chapter31.xhtml: No issues found
verbose: - Processing text/chapter34.xhtml
verbose: Converting aXe results to ace for text/chapter30.xhtml
info:    - text/chapter30.xhtml: No issues found
verbose: - Processing text/chapter35.xhtml
verbose: Converting aXe results to ace for text/chapter32.xhtml
info:    - text/chapter32.xhtml: No issues found
verbose: - Processing text/chapter36.xhtml
verbose: Converting aXe results to ace for text/chapter33.xhtml
info:    - text/chapter33.xhtml: No issues found
verbose: - Processing text/chapter37.xhtml
verbose: Converting aXe results to ace for text/chapter35.xhtml
info:    - text/chapter35.xhtml: No issues found
verbose: - Processing text/chapter38.xhtml
verbose: Converting aXe results to ace for text/chapter34.xhtml
info:    - text/chapter34.xhtml: No issues found
verbose: - Processing text/chapter39.xhtml
verbose: Converting aXe results to ace for text/chapter36.xhtml
info:    - text/chapter36.xhtml: No issues found
verbose: - Processing text/chapter40.xhtml
verbose: Converting aXe results to ace for text/chapter37.xhtml
info:    - text/chapter37.xhtml: No issues found
verbose: - Processing text/chapter41.xhtml
verbose: Converting aXe results to ace for text/chapter41.xhtml
info:    - text/chapter41.xhtml: No issues found
verbose: - Processing text/chapter42.xhtml
verbose: Converting aXe results to ace for text/chapter39.xhtml
info:    - text/chapter39.xhtml: No issues found
verbose: - Processing text/chapter43.xhtml
verbose: Converting aXe results to ace for text/chapter38.xhtml
info:    - text/chapter38.xhtml: No issues found
verbose: - Processing text/chapter44.xhtml
verbose: Converting aXe results to ace for text/chapter40.xhtml
info:    - text/chapter40.xhtml: No issues found
verbose: - Processing text/chapter45.xhtml
verbose: Converting aXe results to ace for text/chapter43.xhtml
info:    - text/chapter43.xhtml: No issues found
verbose: Converting aXe results to ace for text/chapter44.xhtml
info:    - text/chapter44.xhtml: No issues found
verbose: - Processing text/chapter46.xhtml
verbose: - Processing text/chapter47.xhtml
verbose: Converting aXe results to ace for text/chapter45.xhtml
info:    - text/chapter45.xhtml: No issues found
verbose: - Processing text/chapter48.xhtml
verbose: Converting aXe results to ace for text/chapter42.xhtml
info:    - text/chapter42.xhtml: No issues found
verbose: - Processing text/chapter49.xhtml
verbose: Converting aXe results to ace for text/chapter47.xhtml
info:    - text/chapter47.xhtml: No issues found
verbose: - Processing text/chapter50.xhtml
verbose: Converting aXe results to ace for text/chapter46.xhtml
info:    - text/chapter46.xhtml: No issues found
verbose: - Processing text/chapter51.xhtml
verbose: Converting aXe results to ace for text/chapter50.xhtml
info:    - text/chapter50.xhtml: No issues found
verbose: - Processing text/chapter52.xhtml
verbose: Converting aXe results to ace for text/chapter49.xhtml
info:    - text/chapter49.xhtml: No issues found
verbose: - Processing text/chapter53.xhtml
verbose: Converting aXe results to ace for text/chapter48.xhtml
info:    - text/chapter48.xhtml: No issues found
verbose: - Processing text/chapter54.xhtml
verbose: Converting aXe results to ace for text/chapter51.xhtml
info:    - text/chapter51.xhtml: No issues found
verbose: - Processing text/chapter55.xhtml
verbose: Converting aXe results to ace for text/chapter53.xhtml
info:    - text/chapter53.xhtml: No issues found
verbose: - Processing text/chapter56.xhtml
verbose: Converting aXe results to ace for text/chapter52.xhtml
info:    - text/chapter52.xhtml: No issues found
verbose: - Processing text/chapter57.xhtml
verbose: Converting aXe results to ace for text/chapter54.xhtml
info:    - text/chapter54.xhtml: No issues found
verbose: - Processing text/chapter58.xhtml
verbose: Converting aXe results to ace for text/chapter55.xhtml
info:    - text/chapter55.xhtml: No issues found
verbose: - Processing text/chapter59.xhtml
verbose: Converting aXe results to ace for text/chapter57.xhtml
info:    - text/chapter57.xhtml: No issues found
verbose: - Processing text/chapter60.xhtml
verbose: Converting aXe results to ace for text/chapter56.xhtml
info:    - text/chapter56.xhtml: No issues found
verbose: - Processing text/chapter61.xhtml
verbose: Converting aXe results to ace for text/chapter58.xhtml
info:    - text/chapter58.xhtml: No issues found
verbose: - Processing text/chapter62.xhtml
verbose: Converting aXe results to ace for text/chapter60.xhtml
info:    - text/chapter60.xhtml: No issues found
verbose: - Processing text/chapter63.xhtml
verbose: Converting aXe results to ace for text/chapter61.xhtml
info:    - text/chapter61.xhtml: No issues found
verbose: - Processing text/chapter64.xhtml
verbose: Converting aXe results to ace for text/chapter59.xhtml
info:    - text/chapter59.xhtml: No issues found
verbose: - Processing text/chapter65.xhtml
verbose: Converting aXe results to ace for text/chapter62.xhtml
info:    - text/chapter62.xhtml: No issues found
verbose: - Processing text/chapter66.xhtml
verbose: Converting aXe results to ace for text/chapter63.xhtml
info:    - text/chapter63.xhtml: No issues found
verbose: - Processing text/chapter67.xhtml
verbose: Converting aXe results to ace for text/chapter64.xhtml
info:    - text/chapter64.xhtml: No issues found
verbose: - Processing text/chapter68.xhtml
verbose: Converting aXe results to ace for text/chapter65.xhtml
info:    - text/chapter65.xhtml: No issues found
verbose: - Processing text/chapter69.xhtml
verbose: Converting aXe results to ace for text/chapter66.xhtml
info:    - text/chapter66.xhtml: No issues found
verbose: - Processing text/chapter70.xhtml
verbose: Converting aXe results to ace for text/chapter68.xhtml
info:    - text/chapter68.xhtml: No issues found
verbose: - Processing text/chapter71.xhtml
verbose: Converting aXe results to ace for text/chapter67.xhtml
info:    - text/chapter67.xhtml: No issues found
verbose: - Processing text/chapter72.xhtml
verbose: Converting aXe results to ace for text/chapter69.xhtml
info:    - text/chapter69.xhtml: No issues found
verbose: - Processing text/chapter73.xhtml
verbose: Converting aXe results to ace for text/chapter70.xhtml
info:    - text/chapter70.xhtml: No issues found
verbose: - Processing text/chapter74.xhtml
verbose: Converting aXe results to ace for text/chapter74.xhtml
info:    - text/chapter74.xhtml: No issues found
verbose: - Processing text/chapter75.xhtml
verbose: Converting aXe results to ace for text/chapter73.xhtml
info:    - text/chapter73.xhtml: No issues found
verbose: Converting aXe results to ace for text/chapter72.xhtml
info:    - text/chapter72.xhtml: No issues found
verbose: - Processing text/chapter76.xhtml
verbose: - Processing text/chapter77.xhtml
verbose: Converting aXe results to ace for text/chapter71.xhtml
info:    - text/chapter71.xhtml: No issues found
verbose: - Processing text/chapter78.xhtml
verbose: Converting aXe results to ace for text/chapter77.xhtml
info:    - text/chapter77.xhtml: No issues found
verbose: - Processing text/chapter79.xhtml
verbose: Converting aXe results to ace for text/chapter78.xhtml
info:    - text/chapter78.xhtml: No issues found
verbose: - Processing text/chapter80.xhtml
verbose: Converting aXe results to ace for text/chapter76.xhtml
info:    - text/chapter76.xhtml: No issues found
verbose: - Processing text/chapter81.xhtml
verbose: Converting aXe results to ace for text/chapter75.xhtml
info:    - text/chapter75.xhtml: No issues found
verbose: - Processing text/chapter82.xhtml
verbose: Converting aXe results to ace for text/chapter79.xhtml
info:    - text/chapter79.xhtml: No issues found
verbose: - Processing text/chapter83.xhtml
verbose: Converting aXe results to ace for text/chapter81.xhtml
info:    - text/chapter81.xhtml: No issues found
verbose: - Processing text/chapter84.xhtml
verbose: Converting aXe results to ace for text/chapter80.xhtml
info:    - text/chapter80.xhtml: No issues found
verbose: - Processing text/chapter85.xhtml
verbose: Converting aXe results to ace for text/chapter82.xhtml
info:    - text/chapter82.xhtml: No issues found
verbose: - Processing text/chapter86.xhtml
verbose: Converting aXe results to ace for text/chapter83.xhtml
info:    - text/chapter83.xhtml: No issues found
verbose: - Processing text/chapter87.xhtml
verbose: Converting aXe results to ace for text/chapter86.xhtml
info:    - text/chapter86.xhtml: No issues found
verbose: - Processing text/chapter88.xhtml
verbose: Converting aXe results to ace for text/chapter84.xhtml
info:    - text/chapter84.xhtml: No issues found
verbose: - Processing text/chapter89.xhtml
verbose: Converting aXe results to ace for text/chapter85.xhtml
info:    - text/chapter85.xhtml: No issues found
verbose: - Processing text/chapter90.xhtml
verbose: Converting aXe results to ace for text/chapter87.xhtml
info:    - text/chapter87.xhtml: No issues found
verbose: - Processing text/chapter91.xhtml
verbose: Converting aXe results to ace for text/chapter89.xhtml
info:    - text/chapter89.xhtml: No issues found
verbose: - Processing text/chapter92.xhtml
verbose: Converting aXe results to ace for text/chapter88.xhtml
info:    - text/chapter88.xhtml: No issues found
verbose: - Processing text/chapter93.xhtml
verbose: Converting aXe results to ace for text/chapter90.xhtml
info:    - text/chapter90.xhtml: No issues found
verbose: - Processing text/chapter94.xhtml
verbose: Converting aXe results to ace for text/chapter91.xhtml
info:    - text/chapter91.xhtml: No issues found
verbose: - Processing text/chapter95.xhtml
verbose: Converting aXe results to ace for text/chapter93.xhtml
info:    - text/chapter93.xhtml: No issues found
verbose: - Processing text/chapter96.xhtml
verbose: Converting aXe results to ace for text/chapter94.xhtml
info:    - text/chapter94.xhtml: No issues found
verbose: - Processing text/chapter97.xhtml
verbose: Converting aXe results to ace for text/chapter92.xhtml
info:    - text/chapter92.xhtml: No issues found
verbose: - Processing text/chapter98.xhtml
verbose: Converting aXe results to ace for text/chapter95.xhtml
info:    - text/chapter95.xhtml: No issues found
verbose: - Processing text/chapter99.xhtml
verbose: Converting aXe results to ace for text/chapter98.xhtml
info:    - text/chapter98.xhtml: No issues found
verbose: - Processing text/chapter100.xhtml
verbose: Converting aXe results to ace for text/chapter96.xhtml
info:    - text/chapter96.xhtml: No issues found
verbose: - Processing text/chapter101.xhtml
verbose: Converting aXe results to ace for text/chapter97.xhtml
info:    - text/chapter97.xhtml: No issues found
verbose: - Processing text/chapter102.xhtml
verbose: Converting aXe results to ace for text/chapter99.xhtml
info:    - text/chapter99.xhtml: No issues found
verbose: - Processing text/chapter103.xhtml
verbose: Converting aXe results to ace for text/chapter100.xhtml
info:    - text/chapter100.xhtml: No issues found
verbose: - Processing text/chapter104.xhtml
verbose: Converting aXe results to ace for text/chapter103.xhtml
info:    - text/chapter103.xhtml: No issues found
verbose: - Processing text/chapter105.xhtml
verbose: Converting aXe results to ace for text/chapter101.xhtml
info:    - text/chapter101.xhtml: No issues found
verbose: - Processing text/chapter106.xhtml
verbose: Converting aXe results to ace for text/chapter102.xhtml
info:    - text/chapter102.xhtml: No issues found
verbose: - Processing text/chapter107.xhtml
verbose: Converting aXe results to ace for text/chapter106.xhtml
info:    - text/chapter106.xhtml: No issues found
verbose: - Processing text/ext_description.xhtml
verbose: Converting aXe results to ace for text/chapter105.xhtml
info:    - text/chapter105.xhtml: No issues found
verbose: Converting aXe results to ace for text/chapter107.xhtml
info:    - text/chapter107.xhtml: No issues found
verbose: Converting aXe results to ace for text/chapter104.xhtml
info:    - text/chapter104.xhtml: No issues found
verbose: Converting aXe results to ace for text/ext_description.xhtml
info:    - text/ext_description.xhtml: No issues found
info:    Consolidating results...
info:    Copying data
error:   Unexpected error: EBUSY: resource busy or locked, copyfile 'C:\Users\AM3617\AppData\Local\Temp\tmp-10480H2yz6sn4eK9d\OEBPS\images\common.jpg' -> 'D:\Rajeshkumar\Works\Test\Ace\report\data\OEBPS\images\common.jpg'
debug:   Error: EBUSY: resource busy or locked, copyfile 'C:\Users\AM3617\AppData\Local\Temp\tmp-10480H2yz6sn4eK9d\OEBPS\images\common.jpg' -> 'D:\Rajeshkumar\Works\Test\Ace\report\data\OEBPS\images\common.jpg'
info:    Closing logs.
Re-run Ace using the --verbose option to enable full debug logging.

Thanks in advance.

Looking forward to receiving your thoughts.

**Comment by rdeltour** [comment] 2018-06-08 07:14
OK thanks, I will try to reproduce locally and will keep you informed!

**Comment by rdeltour** [comment] 2018-06-08 07:52
Unfortunately I couldn’t reproduce (with an EPUB containing 100 files referencing the same 10 MB image).

I can dig deeper, but having access to your sample file would help a lot if you can ask your customer! 😄

**Comment by coolharisha** [comment] 2018-06-08 13:56
@Sorry for convenient, I have created mock-up ePub file for testing purpose. Please share your private mail id to psnharisha@gmail.com. i will share the ePub through your mail id.

**Comment by coolharisha** [comment] 2018-06-08 14:04
@rdeltour Sorry for convenient, I have created mock-up ePub file for testing purpose. Please share your private mail id to psnharisha@gmail.com. i will share the ePub through your mail id.

**Comment by jloier** [comment] 2018-07-19 14:11
Hi

We have the same issue on severals epub files.

We can finally have the report if we launch two times the control on the same output directory, with "-f" argument.

**Comment by danielweck** [comment] 2019-08-10 15:38
Looking at the commit history related to this issue, I am under the impression that this issue has been addressed and can therefore now be closed. It that correct?

**Closed** 2021-04-08 05:24 UTC
