### ISSUE TITLE
0-N footnotes not yet allowed on ONE page

### ISSUE THREAD

**Issue by LaZay** [daisy/ace#300] opened 2019-11-26 19:10 UTC
There is a fake violation on multiple footnotes on the SAME PAGE (which may happen sometimes).
![image](https://user-images.githubusercontent.com/28054954/69663384-6e468980-1086-11ea-8583-e6d4e15d16cb.png)

ACE considers that only one role=doc-footnote [singular] is allowed in the scope of one epub:type=footnote**s** [plural].
Nota1: there is no role=doc-footnotes [plural] in ARIA DPUB values today.
ACE generates the following error :
- error location+code : "Text/notes.xhtml#epubcfi(/4/2/2[notectnr_d14e46]/4/2[note_ntb-1])
- error details: The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable 
![image](https://user-images.githubusercontent.com/28054954/69664397-9505bf80-1088-11ea-9779-7832e75b0f34.png)

Nota2: each footnote may consist into several paragraphs (yes, they can). The semantic attributes epub:type=foonote + role=doc-foonote cannot be placed down to the <p> entering notes' definitions. The <aside>element is the proper element to carry indivual notes semantic attributes.

Nota3: it seems that DPUB / ACE missed something in the editorial needs for a 2 levels vocabulary as defined in epub:type:
- footnotes (container) gathering individual notes on the SAME PAGE;
- footnote (individual notes).
The PAGE does exist in an ePub.

ACE 1.1.1, Node 12.11.1, Windows 7

**Comment by rdeltour** [comment] 2019-11-26 20:45
This violation seems to come from the `landmark-unique` rule from Axe. This is not specifically related to footnotes, but generally checks that all landmarks are properly identifiable (by being the only representative of their role —like `main`— or by having an accessible name —from `aria-label` or `aria-labelledby` for  instance—).

I think the violation would go away if you'd use something else than `aside` to represent the notes in the list. For instance a `p` element.

Also, it seems that by grouping these notes in their own section, maybe `doc-endnotes` is more representative of their role here?

**Comment by rdeltour** [comment] 2019-11-26 20:51
Note that there’s still something a bit wonky, in that by setting a role of `doc-footnote` to the `aside` element, they should no longer be landmarks, so this rule should not be triggered. It’s possible that Axe doesn’t take the DPUB role into account if they’re not supported in some of their target AT+Browser combinations. I'll look into it.

**Comment by laudrain** [comment] 2019-11-27 08:53
I confirm that the rule is to have unique landmark roles. 
Though 'footnote' is not listed in landmark roles (see open issue #271)

The resolution is to add aria-labels to each aside element with a role="doc-footnote".
Like in:

```
    <section class="ntsp" epub:type="footnotes">
        <aside class="ntb" epub:type="footnote" id="ntb-001" role="doc-footnote" aria-label="ntb-001">
                <p class="ntsp-j"><a href="appen6.xhtml#ap_ntb-001-1">*1</a>. Le titre est de
                    l’auteur.</p>
            </aside>
        <aside class="ntb" epub:type="footnote" id="ntb-002" role="doc-footnote" aria-label="ntb-002">
                <p class="ntsp-j"><a href="appen6.xhtml#ap_ntb-002-1">*2</a>. Tous les passages en
                    italique sont soulignés par l’auteur.</p>
            </aside>
        </section>

````

**Comment by rdeltour** [comment] 2019-11-27 09:24
> Though 'footnote' is not listed in landmark roles (see open issue #271)

Yes, that's what I was hinting at in my previous comment: it seems Axe doesn't take into account the DPUB role as overriding the native `aside` role (which is `complementary` and is a landmark role).

My guess is that it's because DPUB ARIA isn't supported in Edge (before the Chromium base) and then doesn't pass their criteria.

> The resolution is to add aria-labels to each aside element with a role="doc-footnote".

Yes, that or using another element than `aside` to represent the footnote. Honestly with a list of footnotes like in your example markups I would rather use `p` elements (or even `div`) rather than an `aside`. I would use `aside` for the whole section however.

```html
    <aside class="ntsp" epub:type="footnotes" aria-label="Footnotes">
        <div class="ntb" epub:type="footnote" id="ntb-001" role="doc-footnote" aria-label="ntb-001">
                <p class="ntsp-j"><a href="appen6.xhtml#ap_ntb-001-1">*1</a>. Le titre est de
                    l’auteur.</p>
            </div>
        <div class="ntb" epub:type="footnote" id="ntb-002" role="doc-footnote" aria-label="ntb-002">
                <p class="ntsp-j"><a href="appen6.xhtml#ap_ntb-002-1">*2</a>. Tous les passages en
                    italique sont soulignés par l’auteur.</p>
            </div>
        </aside>
```

**Comment by rdeltour** [comment] 2019-11-27 09:27
Good catch on this issue being a duplicate of #271. I renamed #271 to be more explicit and will close this one.

**Closed by rdeltour** 2019-11-27 09:27 UTC

**Comment by LaZay** [comment] 2019-11-27 13:58
1. _"The resolution is to add aria-labels to each aside element with a role="doc-footnote"._ 
This is precisely what was done, and what generates the ACE violation.
2. For me, _doc-endnotes_ were reserved to notes gathered at the end of a chapter or a publication. Why ? Because _doc-endnotes_ were volontarily not mapped onto _epub:type=footnotes_ in the epub:type/ARIA DPUB mapping table.
3. _aside_ with _role="doc-footnote"_ cannot be used to tag the **group** of notes. As a matter of fact, _role="doc-footnote"_ is dedicated to **individual** notes.

**Comment by laudrain** [comment] 2019-11-27 14:24
@LaZay sorry but there is no aria-label in the code example you give at the beginning of the issue.
Did you try with ?

**Comment by LaZay** [comment] 2019-11-27 15:02
@laudrain You are right. Sorry, I concentrated on the 2nd part of your answer.
Thanks! The workaround works perfectly. But it is only a workaround.  We should not be forced to set an extra _aria-label_ attribute on each footnote. As a matter of fact, the footnote text already labels the footnote. Adding an _aria-label_ would be a useless extra job. Don't you think?
Plus, we are talking of the footnote **definition**, to be distinguished with the footnote **reference**. Setting the only footnote reference as _aria-label_ value would probably be wrong for visually impaired people.

**Comment by rdeltour** [comment] 2019-11-27 16:00
> We should not be forced to set an extra _aria-label_ attribute on each footnote.

Again, this is only because the element used in your example for the footnote is `aside`, which has a native landmark role (hence requires being labelled to be identifiable by assistive technology).

You can use any other element for the footnote, like `p` or `div`, and group them all in an `aside` instead of `section`; that would be a better markup in my opinion. By using `p` or `div` for the footnotes, you would not need any `aria-label`.

**Comment by LaZay** [comment] 2019-11-27 16:07
For a good digital reading experience, it is necessary to tag each **individual** note with _aside epub:type=footnote_, so each note definition can be individually opened in a pop-up by the reading system.

**Comment by laudrain** [comment] 2019-11-27 18:00
Romain explained why we have to make landmarks unique : 
> aside, which has a native landmark role

So in this case, I din't know if we can qualify this a "workaround".

About noteref, I don't think there is any necessity to put aria-label on their tagging.
In our production, it looks like:
`
<a class="apnote" epub:type="noteref" id="ap_ntb-001-1" href="defNotesDev0.xhtml#ntb-001" role="doc-noteref">*1</a>
`

**Comment by rdeltour** [comment] 2019-11-27 20:40
> For a good digital reading experience, it is necessary to tag each **individual** note with _aside epub:type=footnote_, so each note definition can be individually opened in a pop-up by the reading system.

Ah, I didn't know that… this is bad, but unfortunately there's not much to do about it 😔

**Comment by laudrain** [comment] 2019-11-28 07:21
> it seems Axe doesn't take into account the DPUB role as overriding the native aside role (which is complementary and is a landmark role).

> My guess is that it's because DPUB ARIA isn't supported in Edge (before the Chromium base) and then doesn't pass their criteria.

@rdeltour What is the relation between Axe and Edge?
Is DPUB ARIA more supported in Chromium?

**Comment by LaZay** [comment] 2019-11-28 08:26
@laudrain _About noteref, I don't think there is any necessity to put aria-label on their tagging._
I was not talking about the real _note reference_ which is fine. I was talking about the _note definition_ and **its** _aria-label_ value. It should contain the whole note definition, not only the note reference, otherwise its value would be wrong. Unfortunately, the note definition can be quite long.

**Comment by LaZay** [comment] 2019-11-28 09:10
A better and cheaper workaround would be to set no ARIA role on note definitions tagged with aside.

**Comment by rdeltour** [comment] 2019-11-28 10:13
> @rdeltour What is the relation between Axe and Edge?

Basically, Axe has a principle of only accepting techniques which are proven to work (be "accessibility supported") on widely used browser and AT combinations.

For example, see the [target platforms that are tested for Axe 3.4.0](https://github.com/dequelabs/axe-core/blob/v3.4.0/doc/accessibility-supported.md#accessibility-supported).

Since DPUB ARIA isn’t implemented in IE, for instance, an `aside` with a `doc-footnote` role will not be exposed as a footnote, but as a `complementary` landmark (which is the ARIA role implied on `aside`). So, in order to support users of JAWS+IE, the landmark rules needs to be applied to these `aside` elements.

> Is DPUB ARIA more supported in Chromium?

Yes, I think DPUB ARIA mappings has been added to Chrome (see [chromium issue 839871](https://bugs.chromium.org/p/chromium/issues/detail?id=839871&q=839871&can=2)), but to be honest I cannot find a definitive reference to which accessibility APIs it exposes DPUB ARIA to. The [DPUB AAM 1.0 implementation report](https://w3c.github.io/test-results/dpub-aam/) said at the time that Google “anticipate implementing support for the Digital Publishing ARIA roles in the future”; my understanding is that it is done now.

**Comment by rdeltour** [comment] 2019-11-28 10:43
> For a good digital reading experience, it is necessary to tag each **individual** note with _aside epub:type=footnote_, so each note definition can be individually opened in a pop-up by the reading system.

@LaZay out of curiosity, which reading system require that? Apple iBooks formatting guidelines say:

> When adding pop-up footnotes in EPUB 3 books, you can replace the `<aside>` element with a `<div>` or `<p>` element. Use the `<aside>` element when you want to hide the footnote; use a `<div>` or `<p>` element when you want the footnote to appear in the normal reading view. If you use `<div>` or `<p>` and a user clicks the footnote link, the content appears in a popup, but the footnote is also visible as part of the text on the page.

and I think I read some MobileRead forum thread about `aside` not being always needed either.

**Comment by laudrain** [comment] 2019-12-03 08:24
@rdeltour `aside` element to hide the content of the note in the main text seems to be useful.

Also, quoting Amazon Kindle Guidelines in their last release:
> 10.3.12 Footnote Guidelines
> Amazon strongly recommends marking footnotes with the HTML5 aside element, together with the epub:type attribute. This allows accessible reading systems to ignore the footnotes except when followed by their referents and allows any reading system to handle them more intelligently (e.g., as pop-ups). This usage ensures that even if the EPUB semantic is not recognized, the notes will still be treated as secondary content due the nature of the HTML5 aside element.

**Comment by rdeltour** [comment] 2019-12-03 08:29
yes, but as long as an `aside` is used as a wrapper for a group of notes, the secondary semantics are maintained. Plus, if the note isn't hidden by default in a reading system, you can always hide it with CSS.

I'm not an ebook producer, so my experience is limited. But reading the comments in the MobileRead forum, it seems it's not as simple as "always use aside for individual notes".

**Comment by laudrain** [comment] 2019-12-03 10:54
As @LaZay explained, `aside` is used for each individual note, which may in turn have several paragraphs.
On MobileRead forum, are you refering to:
https://www.mobileread.com/forums/showthread.php?t=304614

**Comment by LaZay** [comment] 2019-12-05 10:55
In an ePub, using aside for a group of notes, is a wrong practise. It should be bannished.

**Comment by rdeltour** [comment] 2019-12-05 12:17
> In an ePub, using aside for a group of notes, is a wrong practise. It should be bannished.

This sound like a very definitive statement. Would you care to elaborate or explain the reasons?

**Comment by LaZay** [comment] 2019-12-05 14:13
laudrain and I already gave you all the reasons why. This sentence is a summary of what we said.
To put it another way, remember that using an aside for a group of notes is a "lazzy" paper-like transposition, that does not convey a nice digital reading experience. Not nice for everybody. And particularly not nice for visually impaired people.
I will try find time to test different reading system so you can experiment this with an ePub for tests. Later on, as I am busy on other stuffs these days.

**Comment by rdeltour** [comment] 2019-12-06 14:25
> laudrain and I already gave you all the reasons why. This sentence is a summary of what we said.

I re-read the thread, and couldn't find a definitive explanation for not using `aside` to wrap a group of footnotes.

There is [this earlier comment](https://github.com/daisy/ace/issues/300#issuecomment-559098251) of yours:

> 2. For me, doc-endnotes were reserved to notes gathered at the end of a chapter or a publication. Why ? Because doc-endnotes were volontarily not mapped onto epub:type=footnotes in the epub:type/ARIA DPUB mapping table.
> 3. aside with role="doc-footnote" cannot be used to tag the group of notes. As a matter of fact, role="doc-footnote" is dedicated to individual notes.

About (2), I would be careful with reading too much into this mapping table, which is after all an informative guide and can always be improved.
The `doc-endnotes` role _could_ make sense to replace `epub:type=footnotes`, depending on the context and the scope of the notes. For instance if all the footnotes are grouped at the end of a big section, that would make sense IMO. 

About (3), it’s true but it doesn’t mean that `aside` **without a role** cannot be used as a wrapper for the group of notes. Like this:

```html
<aside epub:type="footnotes">
   <p id="footnote-1" role="doc-footnote" epub:type="footnote">…</p>
   <p id="footnote-2" role="doc-footnote" epub:type="footnote">…</p>
</aside>
```

Then [you also said](https://github.com/daisy/ace/issues/300#issuecomment-559151101):
> For a good digital reading experience, it is necessary to tag each individual note with aside epub:type=footnote, so each note definition can be individually opened in a pop-up by the reading system.

Is this based on your experience? which reading system have you tested? Would you have the test results available publicly somewhere?

From Luc, the only explanation would be from [his comment about Amazon Kindle Guidelines](https://github.com/daisy/ace/issues/300#issuecomment-561054068). 
If I understand correctly, they recommend using `aside` for its native HTML semantics. This would work too if the individual footnote is a paragraph _inside_ an `aside`.


Again, I'm not a professional EPUB creator, so my experience with interoperability issues is limited. To be perfectly clear I'm not saying you're wrong, all I'm saying is that I lack data or evidence to definitively say  "`aside` for a group of notes is a wrong practise". 

Ideally we would need some extensive testing, with several reading systems and several assistive technology solutions, in order to possibly improve or refine the KB recommendations and the Ace checks.

> To put it another way, remember that using an aside for a group of notes is a "lazzy" paper-like transposition, that does not convey a nice digital reading experience. Not nice for everybody. And particularly not nice for visually impaired people.

I'm not sure I understand what this means. I'm not sure why footnotes grouped in an `aside` would not be "nice" for VI people, when it’s OK for endnotes.

> I will try find time to test different reading system so you can experiment this with an ePub for tests. Later on, as I am busy on other stuffs these days.

Thanks, that would be great! And I understand that this volunteering work is always lower priority and we're all very busy 😊 but help with testing is always welcome! 👍

**Comment by rdeltour** [comment] 2019-12-06 14:26
cc @mattgarrish (as this discussion may lead to improvements to the KB or mapping guide).

**Comment by mattgarrish** [comment] 2019-12-06 19:20
Sorry, I might need someone to condense this discussion.

What I think I'm getting out of it is that axe doesn't consistently report issues but changes whether a document is valid or not based on the browser. Is that true? (Seems frightening, and how is anything not working in Edge representative of a lack of "broad" support given its ~2% market share??) Does the issue go away in another month when the chromium-based Edge is finally released? (i.e., is it worth the effort to do anything about?)

Beyond that, there's no reason you can't have multiple notes inside an aside that I'm aware of. It might well cause issues for pop-up footnotes, but we don't want to police markup that can't be proven to be invalid. We can note the potential problem in the KB, but that's as far as I'd go.

And the mapping guide is not saying that aside is dedicated to doc-footnote or that it is preferred. The table lists the additional elements the role can be used on, beyond all the generic elements listed at the bottom of it. Maybe we need to add a link to the list to every role to make this more explicit (a bit of the redundancy I was trying to avoid, but the asterisk on the column doesn't seem to be working).

Is there anything else I missed here?

**Comment by rdeltour** [comment] 2019-12-08 18:35
@mattgarrish 
> What I think I'm getting out of it is that axe doesn't consistently report issues but changes whether a document is valid or not based on the browser. Is that true?

No, this is not how Axe works. Axe reports the same issues regardless of the browser (to be precise, this is true when the browser in which Axe runs produces the same DOM as in other browsers).

Where the browser matters is for the Axe team to decide if a specific technique has sufficient accessibility support to be deemed acceptable. In other words, if a specific technique isn't accessible in one of the reference browser+AT combination supported by Axe, then Axe will flag the technique as an accessibility violation. For full details on their decision making process, see their doc [“How we make decisions on rules“](https://github.com/dequelabs/axe-core/blob/develop/doc/accessibility-supported.md).

> Beyond that, there's no reason you can't have multiple notes inside an aside that I'm aware of.

Yes, that was my thinking too (but the OP apparently disagree).

I think the KB (coupled with the DPUB ARIA authoring guide) isn’t very clear about that however. Maybe it could include one such example, as it seems that people interpret the current documentation as "doc-footnote must be on an `aside` element". 
This is probably due to the first bullet in the technique:

> Identify footnotes within the text using the `aside` element.

which, if I understand correctly, rather means:

> When individual footnotes are interspersed in the primary text content, identify them with the `aside` element.

Correct?

@mattgarrish: 
> It might well cause issues for pop-up footnotes, but we don't want to police markup that can't be proven to be invalid. We can note the potential problem in the KB, but that's as far as I'd go.

Yes, maybe a note would be useful.

A more serious issue would be if pop-up footnotes would actually cause accessibility issues themselves, as they would not be a thing to wish for.  (I heard that could cause issues with some screen readers, but didn't have the time to double check).

> And the mapping guide is not saying that aside is dedicated to doc-footnote or that it is preferred. The table lists the additional elements the role can be used on, beyond all the generic elements listed at the bottom of it. Maybe we need to add a link to the list to every role to make this more explicit (a bit of the redundancy I was trying to avoid, but the asterisk on the column doesn't seem to be working).

Yeah, apparently the mapping guide is sometimes taken very strictly, so being explicit about the generic elements sounds like a useful improvement to me. Maybe more examples, too? (but then there's a risk of overlap with the KB!).
