### ISSUE TITLE
Question - possible non localized strings

### ISSUE THREAD

**Issue by thiagoeec** [daisy/ace#266] opened 2019-08-05 10:40 UTC
These two strings are not being localized even when using a language available for both Ace and Axe:

`Fix any of the following / Fix all of the following`

They appear on the report and I'm not sure either they are issued by Ace or Axe.
Looking at the code below, I can see they have been removed from Axe messages, but I couldn't find a insertion point later, which I presume to exist since the strings are present both on Html and Json reports.

https://github.com/daisy/ace/blob/bf8b37442d5557d056d131057a8213ba24334c6e/packages/ace-report-axe/src/index.js#L106-L117

**Comment by danielweck** [comment] 2019-08-05 11:06
The Ace code removes these Axe strings using a regular expression, as per the code snippet you quoted.
If the Axe strings still appear in the JSON and/or HTML reports, then this is a bug.
Unfortunately I am not able to reproduce this bug. Could you please share an EPUB publication with which you are able to observe this problem?
Many thanks!

**Comment by danielweck** [comment] 2019-08-05 11:21
I confirm that when the regular expression code is disabled, then the redundant Axe string appears in the Ace report (`dct:description`). So, the existing Ace code seems to do its job correctly.
I tested this with the `master` branch.

**Comment by danielweck** [comment] 2019-08-05 11:26
In addition to testing with the `master` branch, I also tested the latest published NPM `@daisy/ace-cli` package:
`npx @daisy/ace-cli -o ~/Desktop/ -f -V ~/Desktop/book.epub`
This is version `1.1.1`:
https://unpkg.com/browse/@daisy/ace-cli@1.1.1/

**Comment by thiagoeec** [comment] 2019-08-05 14:53
Hi, @danielweck .

I'm getting this message always in english. I've tested it with the latest `NPM package (1.1.1)` and ` master` branch.
I've attached a sample file (scramble) that will raise this kind of error. Also, see this screenshot:

![report](https://user-images.githubusercontent.com/12530711/62473546-582f5900-b777-11e9-900f-0eb98c9760df.png)


Test file:
[Test.zip](https://github.com/daisy/ace/files/3468106/Test.zip)

**Comment by thiagoeec** [comment] 2019-08-05 14:56
JSON file:

```
{
          "@type": "earl:assertion",
          "earl:result": {
            "earl:outcome": "fail",
            "dct:description": "L’élément est dans l’ordre de tabulation et n’a pas d’intitulé accessible\n\nFix any of the following:\n  L’élément n’a aucun contenu textuel visible par les lecteurs d’écran\n  L’attribut aria-label n’existe pas ou est vide\n  L’attribut aria-labelledby n’existe pas, fait référence à des éléments qui n’existent pas ou à des éléments vides ou non visibles\n  La sémantique par défaut de l’élément n’est pas annulée avec role=\"presentation\"\n  La sémantique par défaut de l’élément n’est pas annulée avec role=\"none\"",
            "earl:pointer": {
              "cfi": [
                "/4/2/10/2"
              ],
              "css": [
                ".redes-sociais > a:nth-child(1)"
              ]
            },
```

**Comment by danielweck** [comment] 2019-08-05 21:09
Thank you, with your EPUB I am able to reproduce the bug. Looking into it...

**Comment by danielweck** [comment] 2019-08-05 21:24
Fixed via https://github.com/daisy/ace/pull/267

**Closed** 2019-08-05 21:24 UTC
