### ISSUE TITLE
Down grade the ACE checker version

### ISSUE THREAD

**Issue by christoberaps** [daisy/ace#256] opened 2019-07-25 12:17 UTC
Recently I installed node.js and installed daisy ace checker by running
`npm install @daisy/ace -g`

So by default, the latest version got installed but I would like to install the previous version from the latest version.

Can someone guide me how can we achieve this?

Thanks,
Christober

**Comment by danielweck** [comment] 2019-07-25 12:34
Click on the "Versions" tab to see what packages have been officially published to NPM, and choose the version you want:

https://www.npmjs.com/package/@daisy/ace

1) Uninstall your currently-installed version: `npm remove --global @daisy/ace`

2) Install the version you want, for example: `npm install --global @daisy/ace@1.1.1`

Just out of interest, what is the reason for *not* wanting / being able to use the latest version `1.1.1`?

**Comment by danielweck** [comment] 2019-08-09 08:31
Closing this as answered, but feel free to reopen if necessary. :)

**Closed by danielweck** 2019-08-09 08:31 UTC

**Comment by rdeltour** [comment] 2019-08-09 09:15
@danielweck I'm not sure that installing a specific older version (à la `npm i -g @daisy/ace@x.y.z`) will effectively revert the packages, since we specify cross-package dependencies with caret version ranges (`^x.y.z`).

If we'd want to tie a given `@daisy/ace` version to specific versions of its dependent ace packages, shouldn't we start using stricter version ranges for the dependencies? Using tilde versions (`~x.y.z`) could be a good compromise. WDYT?

**Comment by danielweck** [comment] 2019-08-09 09:50
That's a good point.

Short answer: `yarn --frozen-lockfile` or `npm ci`

Longer answer:

* With Ace App (`ace-gui` project), there is reliable control over what precise NPM package versions are distributed as part of the build artefact (i.e. application installers), thanks to the "lock file" (in our case, `yarn.lock`, but could be vanilla `package-lock.json` too). Note that `npm ci` imposes even more stringent package resolution heuristics compared with `npm install` ... but this is a built-time concern, not a deployment-time one (same remark with `yarn --frozen-lockfile`).
* Conversely with Ace CLI (`ace` project), distribution of the "executable" software is via the NPM service itself (or the alternative Yarn registry) - i.e. `npm install` or `yarn` equivalent - , which means that package resolution is dependent on the NPM/Yarn algorithm, based on (if I am not mistaken) fluid semantic versioning rather than the "frozen" representation provided by a lockfile. In other words, users installing `ace-cli` at different points in time may get different executable code, due to transitive dependencies resolved deep in the package tree. It is technically possible to package `ace-cli` as a "frozen" set of dependencies (i.e. a proper app-like distribution), but this would require an extra build step, and more importantly the user experience would diverge from the current `npm/yarn install ace` approach. In that light, `yarn --frozen-lockfile` or `npm ci` seems like a safer bet. To be tried.

**Comment by rdeltour** [comment] 2019-08-09 10:02
> * In that light, `yarn --frozen-lockfile` or `npm ci` seems like a safer bet

I'm not sure how that would work, but I admit I'm not familiar with these options or commands.

With a global install (e.g. `yarn global add @daisy/ace@x.y.z`), wouldn't `--frozen-lockfile` use the single global lockfile, hence would try to use the versions computed in the previous install?

**Comment by danielweck** [comment] 2019-08-09 10:05
My thoughts exactly. `yarn global add ...` or `npm --global install/ci ...` probably do not implement `yarn --frozen-lockfile ...` or `npm ci ...` in the same way as for a local `node_modules` tree of dependencies, for a specific project with a root `package.json` and associated `yarn.lock` / `package-lock.json`.

**Comment by danielweck** [comment] 2019-08-09 10:08
Something to consider for users who wish to "freeze" `ace-cli` just as if it was a proper distributable app?
https://github.com/zeit/pkg/blob/master/README.md
(there are other options, but this one immediately came to mind)

Otherwise, I am afraid that when using `ace` as part of the NPM/Yarn ecosystem means accepting the possible variance due to semantic versioning.

**Comment by danielweck** [comment] 2019-08-09 10:58
Note that there is no NPM/Yarn lockfile in the published package (at the registry) at the moment:

https://unpkg.com/browse/@daisy/ace-cli@1.1.1/

**Comment by rdeltour** [comment] 2019-08-09 10:59
I had tried to use Zeit's `pkg`in the past to produce a single binary, but without success (due to the bundling of Chromium if I remember correctly). I hadn't tried very hard though (just ran the basic command), so it may be worth revisiting.

Anyways, as said above I think we could at least use stricter version ranges, like tilde versions instead of caret versions.

**Comment by rdeltour** [comment] 2019-08-09 11:03
> Note that there is no NPM/Yarn lockfile in the published package (at the registry) at the moment

Right. As far as I understand the lock file isn't meant to be published to the npm repo, but to the source code repo. In other words, it's meant for reproducible builds, not reproducible installs.

**Comment by rdeltour** [comment] 2019-08-09 11:05
From [npm's package-lock.json documentation](https://docs.npmjs.com/files/package-lock.json):

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

**Comment by rdeltour** [comment] 2019-08-09 11:06
For publishing a fixed dependency set to npm we would rather use `npm-shrinkwrap.json`:

> It shares a format with `npm-shrinkwrap.json`, which is essentially the same file, but allows publication. This is not recommended unless deploying a CLI tool or otherwise using the publication process for producing production packages.

**Comment by danielweck** [comment] 2019-08-09 11:28
`npm-shrinkwrap.json` seems to fit the bill.
