### ISSUE TITLE
"landmark-unique" rule triggered even if the `doc-footnote` role is set on `aside` elements

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#271] opened 2019-08-14 10:20 UTC
Please provide the following details if possible or relevant:

- [1.1.1] the version of Ace impacted by the issue (as returned by the `ace -v` command).
- [] the version of Node used to run Ace (as returned by the `node -v` command).
- [MacOS Mojave 10.14.6] your operating system and version.
- [] if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).
- [] if the issue is about the HTML report: the browser(s) and version(s) you used.
- [] if possible, let us know if you can share a sample input file to help us reproduce the issue.

I have a Best Practices Ace violation on the rule "landmark-unique".
It is on footnotes that are coded in aside elements :
```
<aside class="ntb" epub:type="footnote" id="ntb-001" role="doc-footnote">
    <p class="ntsp"><a href="chap1.xhtml#ap_ntb-001-1">1</a>. William Fraser est un ancien joueur de rugby ayant évolué au niveau national en Angleterre (<i class="italic">N.d.l.T.</i>).</p>
  </aside>
  <!--note-->
  <aside class="ntb" epub:type="footnote" id="ntb-002" role="doc-footnote">
    <p class="ntsp"><a href="chap1.xhtml#ap_ntb-002-1">2</a>. James Martin et Antony Worrall Thompson sont des chefs cuisiniers britanniques qui participent à des émissions de télévision en rapport avec la cuisine (<i class="italic">N.d.l.T.</i>).</p>
  </aside>
```

The solution is to add aria-label attributes to make these "landmark role" unique:
```
<aside class="ntb" epub:type="footnote" id="ntb-001" role="doc-footnote" aria-label="ntb-001">
    <p class="ntsp"><a href="chap1.xhtml#ap_ntb-001-1">1</a>. William Fraser est un ancien joueur de rugby ayant évolué au niveau national en Angleterre (<i class="italic">N.d.l.T.</i>).</p>
  </aside>
  <!--note-->
  <aside class="ntb" epub:type="footnote" id="ntb-002" role="doc-footnote" aria-label="ntb-002">
    <p class="ntsp"><a href="chap1.xhtml#ap_ntb-002-1">2</a>. James Martin et Antony Worrall Thompson sont des chefs cuisiniers britanniques qui participent à des émissions de télévision en rapport avec la cuisine (<i class="italic">N.d.l.T.</i>).</p>
  </aside>
```
It took me some time to understand what was the issue as there is no specific entry in the knowledge base.
And the "EPUB Type to ARIA Role Authoring Guide" in its [section 4](https://idpf.github.io/epub-guides/epub-aria-authoring/#sec-hd) does list only 3 the "landmark role" values : 

> If a landmark role (e.g., doc-chapter, doc-part, doc-index) does not include a label, assistive technologies will not include it in the list of landmarks.

Is there a complete list of all "landmark role" values somewhere ?

**Comment by laudrain** [comment] 2019-09-11 08:45
@rdeltour this issue relates to the one of Charles [issue 273](https://github.com/daisy/ace/issues/273).

Can someone bring an answer to the question here: is there a complete list of all "landmark role" values somewhere ?
@mattgarrish @danielweck @clapierre

**Comment by rdeltour** [comment] 2019-09-11 09:08
> is there a complete list of all "landmark role" values somewhere ?

The list of ARIA 1.1 landmark roles is summarized in ARIA 1.1 [section 5.3.4. “Landmark Roles”](https://www.w3.org/TR/wai-aria-1.1/#landmark_roles):

- `banner`
- `complementary`
- `contentinfo`
- `form`
- `main`
- `navigation`
- `region`
- `search`

For DPUB ARIA, there is no such list summary, so you have to look at the roles which have a superclass role of `landmark`, or of another role itself subclassing a landmark. These are the landmark roles I found in DPUB ARIA  1.0:

- `doc-acknowledgments`
- `doc-afterwords`
- `doc-appendix`
- `doc-bibliography`
- `doc-chapter`
- `doc-conclusion`
- `doc-credits`
- `doc-endnotes`
- `doc-epilogue`
- `doc-errata`
- `doc-foreword`
- `doc-glossary`
- `doc-index` (`navigation` superclass role)
- `doc-introduction`
- `doc-pagelist`
- `doc-part`
- `doc-preface`
- `doc-prologue`
- `doc-toc`

It would probably be useful to document this list somewhere, like on the KB (cc @mattgarrish).

**Comment by danielweck** [comment] 2020-04-13 11:15
Hello Romain, if I understand correctly, this is not a bug in Ace? Can we close this issue?

**Comment by rdeltour** [comment] 2020-04-13 13:17
Well, it depends if we want to loosen the Axe rules. 

Basically, Axe checks that for each kind of landmark, there is either a unique occurence or a non-ambiguous title. The problem here is that `doc-footnote` is not recognized by Axe as a landmark, so the unicity rule is checked along with the other `aside` elements.

We can either decide to apply Axe's default logic, the rationale being that DPUB ARIA isn't sufficiently supported so the logic has to be applied as if the role wasn't set.
Or we decide to overrule Axe, in which case we need to patch it to make it aware of the DPUB ARIA role.

**Comment by danielweck** [comment] 2020-04-13 14:59
Thank you very much Romain, this helps.

**Comment by jenstroeger** [comment] 2020-09-22 22:41
I ran into an issue that seems related to this one. Bookalope generates footnotes as follows:
```html
<aside epub:type="footnote" role="doc-footnote" aria-label="Footnote 1" id="fn-1">
  <p><a href="#fn-ref-1" role="doc-backlink" title="Go back to reference for this footnote 1.">1.</a> … </p>
</aside>
```
Feedback from an A11y QA tester was

> You don’t need an aria label; this is just repetitive info since the numbers will already be announced to readers. So it should be simply: `<aside epub:type="footnote" role="doc-footnote" id="fn-1”>`

However, without that aria label Ace complains that the “landmark-unique” rule was violated:
```json
{
  "@type": "earl:assertion",
  "earl:result": {
    "earl:outcome": "fail",
    "dct:description": "The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable",
    "earl:pointer": {
      
    },
    "html": "..."
  },
  "earl:assertedBy": "aXe",
  "earl:mode": "automatic",
  "earl:test": {
    "earl:impact": "moderate",
    "dct:title": "landmark-unique",
    "dct:description": "Landmarks must have a unique role or role/label/title (i.e. accessible name) combination",
    "help": {
      "url": "http://kb.daisy.org/publishing/",
      "dct:title": "(no specific entry)",
      "dct:description": "Ensures landmarks are unique"
    },
    "rulesetTags": [
      "cat.semantics",
      "best-practice"
    ]
  }
}
```
@rdeltour, if I understand your [above comment](https://github.com/daisy/ace/issues/271#issuecomment-612893757) correctly then this is something that Ace needs to/should address? We can ignore this particular warning for now?

**Comment by marisademeglio** [comment] 2020-09-29 17:28
Does putting the footnote in an aside instead of a different element enable certain reading system behaviors? We had [another thread](https://github.com/daisy/ace/issues/300) about this too, nothing definitive there though.

**Comment by clapierre** [comment] 2021-01-21 15:43
So this is the same issue then if you have `<aside role="doc-example">...` since doc-example has as its superclass Role as "section" the same as doc-footnote has as its superclass Role of Section.

**Comment by danielweck** [comment] 2021-04-07 05:30
> doc-example has as its superclass Role as "section"

Note that DPUB ARIA 1.1 changed `section` to super class role `figure`:

https://www.w3.org/TR/dpub-aria-1.0/#doc-example
=>
https://w3c.github.io/dpub-aria/#doc-example

**Comment by danielweck** [comment] 2021-04-07 06:24
I think I found the bug in Axe which causes element types to be considered landmarks when they shouldn't. I am pushing a fix.

**Comment by danielweck** [comment] 2021-04-07 14:04
Ace `1.2.0-beta.14` addresses a number of issues around DPUB ARIA role mappings. Available from NPM:
https://www.npmjs.com/package/@daisy/ace/v/next

I should be done within the next few hours with the Ace core / CLI updates, at which point I will replace v1.1.1 on NPM with the latest (and hopefully greatest) v1.2

**Closed** 2021-04-07 14:04 UTC
