### ISSUE TITLE
Unexpected error: Failed to launch chrome!

### ISSUE THREAD

**Issue by Exelenz9** [daisy/ace#165] opened 2018-01-30 09:38 UTC
Hello. 
Getting this error while trying to run `ace`. Full message:

> yart@yart-K53SV:~/work_lnk$ ace -o ace/ -f -V Downloads/Sample\ book\ \(2\).epub 
> verbose: ACE cwd=/media/winb/Work, outdir=ace/, tmpdir=undefined, verbose=true, silent=false, jobId=
> info:    Processing Downloads/Sample book with radio and checkbox (2).epub
> verbose: Extracting EPUB
> info:    Parsing EPUB
> verbose: at location '/tmp/tmp-59576sQyuHbK67kD'
> info:    Analyzing accessibility metadata
> info:    Checking package...
> info:    - OEBPS/content.opf: No issues found
> error:   Unexpected error: Failed to launch chrome!
> /home/yart/.nvm/versions/node/v8.9.4/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-526987/chrome-linux/chrome: 3: /home/yart/.nvm/versions/node/v8.9.4/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-526987/chrome-linux/chrome: Syntax error: ")" unexpected
> 
> TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
> 
> debug:   Error: Failed to launch chrome!
> /home/yart/.nvm/versions/node/v8.9.4/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-526987/chrome-linux/chrome: 3: /home/yart/.nvm/versions/node/v8.9.4/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-526987/chrome-linux/chrome: Syntax error: ")" unexpected
> 
> TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
> 
>     at onClose (/home/yart/.nvm/versions/node/v8.9.4/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/Launcher.js:226:14)
>     at Interface.helper.addEventListener (/home/yart/.nvm/versions/node/v8.9.4/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/Launcher.js:215:50)
>     at emitNone (events.js:111:20)
>     at Interface.emit (events.js:208:7)
>     at Interface.close (readline.js:370:8)
>     at Socket.onend (readline.js:149:10)
>     at emitNone (events.js:111:20)
>     at Socket.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1055:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
> info:    Closing logs.
> Re-run Ace using the --verbose option to enable full debug logging.

Probably, this is a question to a GoogleChrome, but maybe someone knows the solution, as `ace` uses specified version of `puppeteer`.
System:

- ace - `1.0.0-RC.1`
- Node - `v8.9.4`
- npm - `5.6.0`
- Ubuntu 16.04, 32

Tested on different input files and different Node/npm versions - getting the same error. Could this be a problem, that I'm using Ubuntu x32?

**Comment by rdeltour** [comment] 2018-01-30 10:37
Thanks for the report! 👍

> Could this be a problem, that I'm using Ubuntu x32?

It might be. Ace is tested on Ubuntu 64bits and `puppeteer` can launch Chrome successfully there (with sandbox disabled). I’ll try to install a 32bit Ubuntu to see if I can reproduce!

**Comment by seanharrison** [comment] 2018-05-10 02:46
I ran into the same issue – Ubuntu 18.04 64bit, node 8.10.0, npm 3.5.2. Would love to resolve this issue. Any suggestions?

    ~$ node --version
    v8.10.0
    ~$ npm --version
    3.5.2
    ~$ uname -m
    x86_64
    ~$ ace -V -f -o *****.epub
    verbose: Ace 1.0.0, Node v8.10.0, Linux 4.15.0-20-generic
    verbose: Options: cwd=/home/bg, outdir=*****_ACE, tmpdir=undefined, verbose=true, silent=false, jobId=
    info:    Processing *****.epub
    verbose: Extracting EPUB
    info:    Parsing EPUB
    verbose: at location '/tmp/tmp-10819s6acFbKKlh1h'
    info:    Analyzing accessibility metadata
    info:    Checking package...
    info:    - Exemplar_EPUB.opf: 4 issues found
    error:   Unexpected error: Failed to launch chrome!
    /usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-555668/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory


    TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    debug:   Error: Failed to launch chrome!
    /usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-555668/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory


    TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

        at onClose (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/Launcher.js:255:14)
        at Interface.helper.addEventListener (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/Launcher.js:244:50)
        at emitNone (events.js:111:20)
        at Interface.emit (events.js:208:7)
        at Interface.close (readline.js:370:8)
        at Socket.onend (readline.js:149:10)
        at emitNone (events.js:111:20)
        at Socket.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
    info:    Closing logs.
    Re-run Ace using the --verbose option to enable full debug logging.
    ~$

**Comment by rdeltour** [comment] 2018-05-18 22:54
@seanharrison it doesn't seem to be the exact same issue as @Exelenz9 above.
Could you please try running `ldd chrome | grep not` to see if you have missing Chrome dependencies?

**Comment by seanharrison** [comment] 2018-05-19 13:16
Thanks, Romain – I didn't realize I needed to install Chrome on the system, which did the job. I wonder if it's possible to use Chromium via npm instead so that it's all managed by npm/yarn.

**Comment by rdeltour** [comment] 2018-05-20 18:11
> I didn't realize I needed to install Chrome on the system, which did the job.

You shouldn’t _have to_ install Chrome. But apparently the Chromium version installed as a dependency of Puppeteer (Google’s API to drive headless chromium) was missing some libraries, and I guess that these were installed when you installed Chrome, which effectively fixed the issue.

> I wonder if it's possible to use Chromium via npm instead so that it's all managed by npm/yarn.

The node install script of Puppeteer does fetch Chromium. That said, maybe there is another package of Chromium with a more thorough install step that could fix these library dependencies issues?

**Comment by bitsgalore** [comment] 2018-05-30 14:26
FWIW I'm still getting this error with the latest (1.0.2) version of ace. In my case installing Chrome didn't help. Running `ldd chrome | grep not`  (or more specifically in my case: `ldd /opt/google/chrome/chrome | grep not`) worked, but produced no output  (so apparently all dependencies are there?).

* ace 1.0.2
* node v8.11.2
* npm 5.6.0
* Linux Mint 18.3 (Sylvia)

**Comment by bitsgalore** [comment] 2018-11-06 16:01
Update: the issue appears to be caused (at least for me) by permissions on files and/or directories. See also this link:

<https://github.com/GoogleChrome/puppeteer/issues/2519>

The solution that is mentioned there doesn't quite work for me (can't find a directory `/usr/local/lib/node_modules/puppeteer/.local-chromium`on my machine), but if I run Ace as sudo:

    sudo ace anro001bioe01_01.epub -o ./aceReport

it runs without any issues. Of course I don't really *want* to run ace as sudo, so I'll have another go at finding the root cause (i.e. the exact files/directories for which the permissions are wrong). But this should at least point others who run into this issue in the right direction.

**Comment by rdeltour** [comment] 2018-11-06 20:00
> if I run Ace as sudo it runs without any issues

Intersesting, thanks for the follow-up!

If you installed Ace with `npm`, you could possibly customize the npm global directory to a place where you have the right permissions… see the possibilities mentioned in [the NPM doc](https://docs.npmjs.com/getting-started/fixing-npm-permissions).

**Comment by danielweck** [comment] 2021-04-08 05:43
See resolution in https://github.com/daisy/ace/issues/340

**Closed by danielweck** 2021-04-08 05:43 UTC
Labels: bug
