### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by thiagoeec** [daisy/ace#233] opened 2019-05-12 09:28 UTC
I checked a book with this "cover.xhtml" file:

```
<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="pt-BR" xml:lang="pt-BR">
	<head>
		<title>Capa</title>
		<link href="../Styles/Frontmatter.css" rel="stylesheet" type="text/css"/>
	</head>
	<body lang="pt-BR" xml:lang="pt-BR">
    <section epub:type="frontmatter cover" aria-labelledby="capa_do_livro" aria-describedby="desc_capa" id="id-a">
      <div class="Cover">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" viewBox="0 0 811 1200">
          <title id="capa_do_livro">Capa do livro A Viagem de Théo</title>
          <desc id="desc_capa">Fundo preto com faixa amarela no topo com vários desenhos de templos religiosos um ao lado do outro.</desc>
          <image role="doc-cover" width="811" height="1200" xlink:href="../Images/cover.jpg"/>
        </svg>
      </div>
    </section>
	</body>
</html>
```

I can't see nothing wrong with it. The "doc-cover" role is used on the image, as suposed to.  But ACE (GUI) gives me this error:
```
Moderate | wcag2a | aria-dpub-role-fallbackVia:aXe | Text/Capa.xhtml#epubcfi(/4/2[id-a]/2/2/6)<image xmlns="http://www.w3.org/2000/svg" role="doc-cover" width="811" height="1200" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="../Images/cover.jpg"/> | Element’s implicit ARIA role is not a good fallback for the (unsupported) role. Learn about: (no specific entry)
```

I don't really understand this error. There is no fallback. Also, when I check it with the command line tool, I get no error.

**Comment by danielweck** [comment] 2019-05-13 08:34
I have transferred this issue from `ace-gui` to `ace`.
CC @rdeltour

**Comment by thiagoeec** [comment] 2019-05-13 10:39
> Hello! :) Which version / release of Ace-GUI are you using?

Sorry. I forget the details.

Ace: 1.0.2 (installed with npm)
Ace GUI: 1.0.0-beta.2
OS: Windows 10 x64

> Note that the latest Ace revision from the GitHub repository (not yet officially published as an NPM package) incorrectly reports issues related to epub:type and ARIA mappings.
See: #201

I've notice that on a few circunstances. But like I said, the Command Line Ace does not gave me the error. The error only appeared on the GUI. Does the GUI use the newer updated ACE (still not available via from npm)? If not, then the bug belongs to the GUI, not ACE itself.

**Comment by danielweck** [comment] 2019-05-13 10:57
This bug definitely belongs here, in Ace "core" :)
The GUI app does not implement any checking/validation logic, it delegates all the work to Ace core (with Axe, under the hood).
The Ace "core" NPM packages have not been updated yet, but you can run the Ace CLI from the GitHub codebase directly, and you will see the same results as Ace GUI.

**Comment by thiagoeec** [comment] 2019-05-13 11:56
> This bug definitely belongs here, in Ace "core" :)

Ok. It is using the updated code, then.

> ...you can run the Ace CLI from the GitHub codebase directly, and you will see the same results as Ace GUI.

Oh, and how can run it directly from the codebase? I didn't find any instructions and I am new to this.

**Comment by rdeltour** [comment] 2019-05-13 12:09
This looks like a regression bug that was introduced by our upgrade to Axe v3 in the internal build of `ace-core` used in the latest GUI. At first sight it is not a duplicate of #201, but I will look into it.

@thiagoeec: if you want to test the latest code base, you need to clone the source from GitHub (or download it as a ZIP), and then you can build the code (`yarn install`), and run the CLI (`yarn ace`). That said, we intend to publish a new release of `ace-core` in the coming weeks, notably to fix the overzealous DPUB ARIA checks.

**Comment by thiagoeec** [comment] 2019-07-05 12:25
Was this issue addressed in this last release? It still throws the same error for me.

**Comment by rdeltour** [comment] 2019-07-05 13:32
No, this issue wasn't addressed in v1.1.0. It is in fact more complex than I first thought, let me try to explain:

Because of the limited support for DPUB ARIA roles by AT, we currently report their use on elements which do not have a native semantic role equal to the super role of the DPUB role. In this case, [`doc-cover`](https://www.w3.org/TR/dpub-aria-1.0/#doc-cover) inherits from the role `img`; any use on an element which does not implicitly have the native `img` role will be reported.

The problem in you markup is that the role is used on an **SVG** `image` element, which does not **by default** have an implicit `img` role. In fact, this element can have an `img` role, but only in the case when it is included itself in the accessibility tree (the details on the criteria for meeting these conditions is specified in the [SVG Accessibility Mappings specification](https://w3c.github.io/svg-aam/#details-id-44), which is still a work in progress.

In addition, the `doc-cover` role would be equally reported if set on the parent `svg` element, as this element do not have an implicit `img` role itself.

To be interpreted as an image by AT, it is common and recommended to put the `img` role on the SVG itself. See the article [“Using ARIA to enhance SVG accessibility”](https://developer.paciellogroup.com/blog/2013/12/using-aria-enhance-svg-accessibility/) from Léonie Watson, on TPG’s blog (dating back to 2013, but still relevant).

Ideally, you would be able to set multiple roles on the SVG like `role="doc-cover img"`, so that `img` is used as a fallback when `doc-cover` isn't supported. Unfortunately, the use of multiple roles is not supported on all the major browser+AT combinations (notably on Edge+JAWS, if I remember correctly).

In any case, what I would currently recommend is to simply drop the `doc-cover` role, and add the role  `img` to the SVG elements.

For more information on SVG and accessibility, you can also have a look to the article [“Accessible SVGs”](https://css-tricks.com/accessible-svgs/) by Heather Migliorisi on CSS Tricks (2016), it's well worth the read 😊.

**Comment by rdeltour** [comment] 2019-07-05 13:33
I'm closing the issue as `wontfix` as Ace doesn't deviate from its intents here, but feel free to keep commenting!

**Closed by rdeltour** 2019-07-05 13:33 UTC
Labels: wontfix

**Comment by thiagoeec** [comment] 2019-07-12 14:42
Thanks for the explanation, @rdeltour.
I'll use your advice and go with `role="img"` on the SVG element, dropping the `doc-cover`.

**Comment by danielweck** [comment] 2019-09-24 14:33
Related / same issue: https://github.com/daisy/ace/issues/282
